### ISSUE TITLE
convert to new version of configuration.json

### ISSUE THREAD

**Issue by savoia-dev** [Toberumono/WRF-Runner#2]
good morning,
congratulations for your work.
I want to convert this file into new configuration.json, can you help me?
Thanks

> {
	"general" : {
		"features" : {
			"wget" : true,
			"wps" : true,
			"wrf" : true
		},
		"parallel" : {
			"is-dmpar" : false,
			"boot-lam" : false,
			"processors" : 4
		},
		"cleanup" : true,
		"working-directory" : "/home/desktop/wrf/OUTPUT",
		"keep-logs" : true,
		"always-suffix" : false,
		"max-kept-outputs" : 15
	},
	"paths" : {
		"wrf" : "/home/desktop/wrf/WRFV3",
		"wps" : "/home/desktop/wrf/WPS"
	},
	"grib" : {
		"url" : "http://www.ftp.ncep.noaa.gov/data/nccf/com/gfs/prod/gfs.%tY%tm%td%tH/gfs.t%tHz.pgrb2.0p25.f0%iH",
		"timestep" : {
			"days" : 0,
			"hours" : 3,
			"minutes" : 0,
			"seconds" : 0
		},
		"wrap-timestep" : false
	},
	"timing" : {
		"use-computed-times" : true,
		"rounding" : {
			"enabled" : true,
			"diff" : "current",
			"fraction" : 0.5,
			"magnitude" : "day"
		},
		"offset" : {
			"enabled" : true,
			"days" : 0,
			"hours" : 0,
			"minutes" : 0,
			"seconds" : 0
		},
		"duration" : {
			"days" : 0,
			"hours" : 24,
			"minutes" : 0,
			"seconds" : 0
		}
	}
}

>

**Comment by Toberumono** [comment]
Hello,
It would appear that the automatic upgrader had a small NPE when working with sufficiently old configuration files.  I fixed that in the latest version (7.4.3, released as of 3 minutes ago). After upgrading to that version, simply running it will cause it to upgrade the configuration file automatically.

If you installed using hombrew, running `brew update && brew upgrade && brew cleanup` will do the trick.

I could not help but notice that while you have processors set to 4, is-dmpar is set to false.  In order to take proper advantage of the processors, is-dmpar must be true.

**Comment by savoia-dev** [comment]
**Good Morning,
thanks for the corretion, now  I receive another error**

> dic 17, 2016 10:03:27 PM toberumono.wrf.modules.GRIBModule lambda$downloadGribFile$0
INFORMAZIONI: Transferring: http://www.ftp.ncep.noaa.gov/data/nccf/com/gfs/prod/gfs.2016121700/gfs.t00z.pgrb2.0p25.f000 -> /home/desktop/wrf/OUTPUT/2016-12-17_00_00_00/grib/gfs.t00z.pgrb2.0p25.f000
dic 17, 2016 10:03:27 PM toberumono.wrf.modules.GRIBModule lambda$downloadGribFile$0
INFORMAZIONI: Transferring: http://www.ftp.ncep.noaa.gov/data/nccf/com/gfs/prod/gfs.2016121700/gfs.t00z.pgrb2.0p25.f003 -> /home/desktop/wrf/OUTPUT/2016-12-17_00_00_00/grib/gfs.t00z.pgrb2.0p25.f003
 *** Starting program ungrib.exe ***
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at toberumono.wrf.Simulation.executeModules(Simulation.java:335)
	at toberumono.wrf.WRFRunner.runSimulation(WRFRunner.java:233)
	at toberumono.wrf.WRFRunner.main(WRFRunner.java:90)
Start_date =  2016-12-17_00:00:00 ,      End_date = 2016-12-17_03:00:00
Caused by: java.lang.NullPointerException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)output format is WPS
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
Path to intermediate files is ./
	... 3 more
Caused by: java.lang.NullPointerException
	at toberumono.wrf.modules.WPSModule.getParallel(WPSModule.java:52)
	at toberumono.wrf.modules.WPSModule.execute(WPSModule.java:112)
	at toberumono.wrf.Simulation.executeModule(Simulation.java:359)
	at toberumono.wrf.Simulation.lambda$null$2(Simulation.java:332)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

>

**Comment by Toberumono** [comment]
Sorry about that.  It would appear that I forgot to account for a couple of sections in the upgrader. I've pushed a patch that should fix this particular issue; however, I won't be able to perform detailed troubleshooting for about another 8 hours.  Run `brew update && brew upgrade && brew cleanup` again to get the latest version (7.4.4).

**Comment by savoia-dev** [comment]
**Hello,  I receive another error**
Exception in thread "main" java.lang.UnsupportedClassVersionError: toberumono/wrf/WRFRunner : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**I attach my configuration**


[configuration.zip](https://github.com/Toberumono/WRF-Runner/files/676018/configuration.zip)

**Comment by Toberumono** [comment]
That appears to be a incompatibility between the version of Java used to build the classes and the version of Java used to run them, not a configuration issue.  Do you by chance have multiple versions of Java on your machine? This error would indicate that the class was compiled with Java 8 and run on Java 7 or earlier JVM.

This project requires Java 8 or newer (to check the version, run `java -version`).

If the version that turns up is version 8, try running `brew reinstall json-library lexer namelist-parser structures utils wrf-runner` to rebuild the program.

**Comment by savoia-dev** [comment]
**I fix error, thanks.**
